### ISSUE TITLE
Chris wants the ability to only choose weekend holidays

### ISSUE THREAD

**Issue by Coldboltage** [Coldboltage/skyscanner-plus#2]
### Issue

Currently Skyscanner Plus doesn't have the functionality to allow a user to select fights that operate only on weekends. The following will have to be considered

- Flight starts on a Friday
- Sunday return flight scheduled

At datePage.js, verification should be executed to see if the weekend-only tab has been accepted. This will mean a tab for weekends will need to be created which will be bundled into this issue. 

### Tasks

- [x] Add a boolean for weekend-only flights
- [x] DatePage.js should check if the provided userFlight demands weekend only
- [x] Create a function that checks days
- [x] Friday Depart
- [x] Sunday Return

### Goal

The solution should allow a user to press a single button for weekend-only flights and for the bot to only accept flights which are from Friday to Sunday.

**Comment by Coldboltage** [comment]
The functionality to allow for this has now been created though it is currently in the form of a simple if statement. Another problem was identified where if a user setup a certain date, as the loop would continue, it would bypass an if statement to check if  the last day of the loop had been met so to push the object to Flightscanner. This has been resolved.
